### ISSUE TITLE
Specify warnIfUnsaved Behavior

### ISSUE THREAD

**Issue by svouse** [google/blockly-devtools#116]
Do we want the warning to fire when we change editor views? Do we opt for a smoother flow of warning upon an attempt at closing the application? If so, how do we give useful information about where the unsaved changes are? How do we reconcile multiple facets of the project being unsaved? Does that flow even make sense, or should people simply be expected to save their components and be inconvenienced otherwise? How can we improve upon the warning that comes up when there are technically unsaved changes, but you didn't make changes in the first place? (I'm referring to, in the current web DevTools, when you open the block editor and immediately try to close it and/or switch tabs; I find this unhelpful/annoying, as I don't care to keep technically unsaved changes I never made)

**Comment by AnmAtAnm** [comment]
No such warnings in v3 of dev tools.
