### ISSUE TITLE
Toolbar Navigation

### ISSUE THREAD

**Issue by chynu** [google/blockly-devtools#12]
**Goal:** Make left toolbar have two tabs. One is for block group navigation, the other is for toolbox navigation.
- Tab 1: Blocks
  - Group blocks (the groupings will be directly transferred to .js files for generators)
- Tab 2: Toolbox
  - Group blocks into toolboxes (allows duplicates across toolboxes, will be directly transferred into .xml files)

**Note:** Drag and drop to move blocks between groups/toolboxes will be completed in further iterations.

**Comment by AnmAtAnm** [comment]
The separation would seam to disallow actions such as dragging a block into a toolbox category.

**Comment by rachel-fenichel** [comment]
Seems all right if dragging over a tab opens that tab.

**Comment by chynu** [comment]
We decided to keep it in one tab and have the three top-node "folders" as "Block Library," "Toolbox," and "Workspace".

**Comment by chynu** [comment]
Resolved with navigation tree.
