### ISSUE TITLE
Discuss Alphabetizing

### ISSUE THREAD

**Issue by svouse** [google/blockly-devtools#124]
Determine if the need to alphabetize has implications for the datatypes used in model

**Comment by rachel-fenichel** [comment]
Please record your conclusions here.

**Comment by svouse** [comment]
**Conclusions:**
The contents of ResourceSets and BlockLibraries should be alphabetized. As far as the user is concerned, this quality must be maintained:
- in the NavigationTree
- when elements are exported
From a developer perspective, using dictionaries to manage the contents of sets and libraries makes for straightforward references; however, JavaScript Objects are not ordered. The final decision is to continue using dictionaries; however, before completing operations for which alphabetical order is important, we'll use an array of the sorted the keys to reference the objects in order.
