### ISSUE TITLE
ES5 to ES6

### ISSUE THREAD

**Issue by chynu** [google/blockly-devtools#127]
Namely, changing `factory_utils.js`, `list_element.js`, etc. to ES6 syntax.

**Comment by NeilFraser** [comment]
No longer supporting Internet Explorer?

**Comment by rachel-fenichel** [comment]
Blockly-devtools is the nw.js version, that has local file system access.  The intended audience is much smaller (developers) so we're okay with dropping IE.  The online version of devtools and core blockly still need to work in IE.
