### ISSUE TITLE
Configure BlockDefinition JSON to Suit Library Json

### ISSUE THREAD

**Issue by svouse** [google/blockly-devtools#130]
Such that extending the json object in getBlockArrayJson() yeilds an object of the sort:

< blockType > : {< attributes (from preexisting Block class json formats >}
< other blockType > : {< attributes >}
.
.
.

**Comment by AnmAtAnm** [comment]
Since each `blockType` has a `type` attribute, I think a `[]` array is all that is needed. Plus, we want to retain ordering.
