### ISSUE TITLE
Loading node modules

### ISSUE THREAD

**Issue by chynu** [google/blockly-devtools#14]
In trying to load modules from other files (e.g. use `FileManagerController` in `app_controller.js`), node's `require()` function is not working, nor is JS's `import { Object } from 'file_location'`. 

Currently, all files in `src/` are loaded through script tags in the HTML file. In the future, should be able to use import to limit scope of imports.

Main bugs: `Uncaught SyntaxError: Unexpected token import`, when trying to do 

```JavaScript
import { FileManagerController } from 'src/file_manager_controller';
```

and 

`Uncaught Error: Cannot find module 'src/file_manager_controller'` when trying to do

```JavaScript
const FileManagerController = require('src/file_manager_controller');
```

**Comment by AnmAtAnm** [comment]
Largely resolved via `all_libs_classes_stylesheets.js`.
