### ISSUE TITLE
WorkspaceConfiguration Popup

### ISSUE THREAD

**Issue by chynu** [google/blockly-devtools#141]
Add popup for workspace config so that preview is updated only when creating a new WorkspaceConfig object in completion, or when user clicks on an already defined WorkspaceConfig object in list.

![config 2](https://user-images.githubusercontent.com/13556792/28636472-1974a0c4-71f3-11e7-9a70-c48f38b833a1.png)

**Comment by AnmAtAnm** [comment]
Surpassed by https://github.com/google/blockly-devtools/issues/226
