### ISSUE TITLE
Workspace Editor: Warn User about Variables/Functions

### ISSUE THREAD

**Issue by chynu** [google/blockly-devtools#147]
Since toolbox and workspace editor are being split into two, when a user creates a WorkspaceContents with a variable or function block, there is no way to guarantee that their toolbox will have the variable or function category.

Modify user flow such that at some appropriate point, DevTools warns the user that they need a variables/functions category for the given WorkspaceContents. (Possibly when user exports, there is some warning with a "quick add" function to add either the variables or functions category.)

**Comment by chynu** [comment]
@svouse I'm going to forget this issue tomorrow, so I'm tagging you now so that we'll have a reminder about this. I think this is a pretty significant thing we should resolve.

**Comment by svouse** [comment]
I dig it

**Comment by AnmAtAnm** [comment]
This is a responsibility of the developer to know if they need the categories.
