### ISSUE TITLE
Debug block popup

### ISSUE THREAD

**Issue by svouse** [google/blockly-devtools#154]
Currently the new block popup always warns "this block already exists!". To circumnavigate this issue for the purposes of moving PRs, getLibrary in src/model/block_library_set.js returns null. After fixing the popup, this is to be changed such that the method is actually functional.

**Comment by chynu** [comment]
I vaguely recall debugging this in one of my branches. Does this still happen on develop for you, @svouse?

Edit: on second thought this might be fixed as of #162.

**Comment by chynu** [comment]
Fixed as of #162.
