### ISSUE TITLE
Block Editor: Save Manual Block Definition Edits

### ISSUE THREAD

**Issue by chynu** [google/blockly-devtools#164]
When switching to "manual edits" in the block definition textarea (under the block editor), users can manually type out their block definition (either in JavaScript or JSON).

In both DevTools web & desktop, switching back to automatic code generation (JSON or JavaScript) does not save the edits in manual mode.

**Comment by AnmAtAnm** [comment]
https://github.com/google/blockly/pull/1235 may solve most of this, but updating the preview and block definitions.
