### ISSUE TITLE
Eliminate 'MyFirstToolbox', WSContents', and 'WSConfig'

### ISSUE THREAD

**Issue by svouse** [google/blockly-devtools#187]
The project gets initialized with Toolbox, WorkspaceContents, and Workspaceconfiguration objects entitled 'MyFirstToolbox', WSContents', and 'WSConfig', respectively; however, they are not shown.

**Comment by rachel-fenichel** [comment]
So are they all created when someone creates a new project?

It doesn't seem like a bad idea to have default objects, as long as the user can rename them as needed.  Otherwise you're just making them take an extra step to create those objects.

**Comment by chynu** [comment]
Hm, I was thinking of when a user might want to create only one resource type (e.g. someone who only wants to define blocks). They will end up exporting the dummy model objects and find that there are empty toolboxes/workspace elements in their file system, when all they wanted was a library.

**Comment by rachel-fenichel** [comment]
That problem is better solved by being able to pick what they want to export.  I think defaults are fine.  It also helps people know what things make up a project.

**Comment by svouse** [comment]
Kk- then I'll update this to 'show defaults', since currently the main problem is these resources exist in the modal but aren't reflected in the view

**Comment by chynu** [comment]
SGTM. I'll fix this in #191 then.
