### ISSUE TITLE
Workspace Editor: Wrapper Class for WorkspaceConfiguration & WorkspaceContents

### ISSUE THREAD

**Issue by chynu** [google/blockly-devtools#201]
The user should not know about the division between WorkspaceConfiguration and WorkspaceContents objects. Currently, the model object representing "workspaces" in devtools is actually the WorkspaceContents object with a reference to a WorkspaceConfig object created within the Contents class.

If it is better implementation (up to future developers), create a wrapper class that contains the Contents and Config object as fields.

**Comment by AnmAtAnm** [comment]
Reverting this effort in #236 and splitting the editor views, per #226.
