### ISSUE TITLE
Workspace Factory refuses to export workspace block XML properly

### ISSUE THREAD

**Issue by rdococ** [google/blockly-devtools#307]
EDIT: Turns out I misunderstood what 'workspace blocks' meant. I really need to learn how to understand stuff like this better.

When I export workspace blocks from the Workspace Factory, I end up with an empty XML file. This happens regardless of what blocks I have, whether they're selected in the Block Exporter (which I don't think is relevant, but I will mention it regardless), or whether there are blocks within the categories I have created.

I'm using the online version from the https://blockly-demo.appspot.com/ website.

**Comment by AnmAtAnm** [comment]
File issues related to the online version in the http://github.com/google/blockly repo.  This repo is a slightly different project.
