### ISSUE TITLE
Blockly.utils.genUID is not a function

### ISSUE THREAD

**Issue by stretch07** [google/blockly-devtools#317]
<img width="1738" alt="Screen Shot 2022-10-05 at 11 10 02 AM" src="https://user-images.githubusercontent.com/78528552/194131608-b5a77cbd-ff68-48f1-baa8-3aef15a64bb5.png">
Nothing at all works on blockly developer tools. Odd, because it wasn't happening yesterday. This is on MacOS with Chrome v106

Can anyone reproduce/fix/give me steps to fix?
Thx

**Comment by stretch07** [comment]
Seeing how this repository has had no change in 5 years, is blockly-devtools no longer worked on?
@NeilFraser

**Comment by stretch07** [comment]
<img width="779" alt="Screen Shot 2022-10-05 at 3 32 30 PM" src="https://user-images.githubusercontent.com/78528552/194175918-7f9f57b7-d23c-4913-99c7-9915e207477a.png">
Oh wow, so blockly-devtools seems to be completely outdated (that page on google no longer exists either)
I will submit a PR fixing this.

**Comment by NeilFraser** [comment]
Huh, I wasn't even aware this repo existed.  Let me check with the team...

**Comment by stretch07** [comment]
This repo is outdated actually, so the PR has been moved to google/blockly :)
