### ISSUE TITLE
Refactor Codebase

### ISSUE THREAD

**Issue by chynu** [google/blockly-devtools#44]
Refactor devtools codebase structure to follow:

![devtools_refactor](https://user-images.githubusercontent.com/13556792/27445949-95623a44-5730-11e7-8efd-343df3d97cc5.png)

**Main changes:**
 - Creating individual Project, Library, Toolbox, Workspace classes (part of the model)
 - Clarifying the difference between views and controllers throughout the application
 - Centralizing the application around three main MVC files from which there are other sub-files (see diagram).

**Comment by AnmAtAnm** [comment]
Yay!!!
